In [1]:
import numpy as np

In [11]:
# Wypelnianie tablicy zerami
a=np.zeros((3,3), dtype=int)

#### Numpy as default typuje liczby na floaty


In [7]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
b=np.ones(2)

In [13]:
c=np.empty(3)

In [14]:
c

array([1.09042911e-311, 0.00000000e+000, 1.27366726e+232])

In [21]:
#tworzenie listy od, do z konkretna iloscia punktow
d=np.linspace(1,15,10)

In [22]:
d

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [24]:
d.shape

(10,)

### TIP

jezeli wpiszesz ? i obiekt to dostaniesz opisik

In [30]:
e=np.random.randint(1,7,(10,10))

In [31]:
e

array([[6, 6, 3, 2, 5, 4, 3, 6, 6, 3],
       [6, 1, 1, 6, 4, 1, 5, 1, 5, 3],
       [5, 5, 6, 6, 2, 6, 3, 1, 4, 2],
       [5, 3, 5, 2, 4, 3, 4, 4, 1, 4],
       [1, 5, 5, 2, 4, 2, 3, 1, 3, 3],
       [3, 6, 3, 1, 5, 2, 2, 4, 3, 6],
       [2, 6, 6, 1, 6, 3, 2, 6, 1, 2],
       [3, 5, 6, 1, 6, 4, 1, 1, 5, 4],
       [2, 4, 2, 1, 2, 6, 1, 6, 5, 5],
       [3, 1, 4, 3, 1, 1, 3, 5, 6, 2]])

In [36]:
e[5:,:5]

array([[3, 6, 3, 1, 5],
       [2, 6, 6, 1, 6],
       [3, 5, 6, 1, 6],
       [2, 4, 2, 1, 2],
       [3, 1, 4, 3, 1]])

# Można testować całą tablice na raz

In [39]:
e[e>3]

array([6, 6, 5, 4, 6, 6, 6, 6, 4, 5, 5, 5, 5, 6, 6, 6, 4, 5, 5, 4, 4, 4,
       4, 5, 5, 4, 6, 5, 4, 6, 6, 6, 6, 6, 5, 6, 6, 4, 5, 4, 4, 6, 6, 5,
       5, 4, 5, 6])