Learning numpy library

In [1]:
import numpy as np

Skróty klawiszowe:
-a dodanie komórki nad
-b dodanie komórki pod
-m tryb zapisów
-y tryb kodu
- d d usuwanie
- jeżeli wpiszemy ?obiekt to dostaniemy szczegółowe informacje

In [26]:
#Wypełnianie tablicy zerami
a=np.zeros((3,1),dtype='int8')

In [27]:
a

array([[0],
       [0],
       [0]], dtype=int8)

In [23]:
#zmiana kształtu
a.shape=(1,3)

In [24]:
a.shape

(1, 3)

In [16]:
# funkcja do tworzenia tablicy (od, do, ile elementów)
z=np.linspace(2,111,5)

In [17]:
z

array([  2.  ,  29.25,  56.5 ,  83.75, 111.  ])

In [28]:
lista=[10,20,30,40,50]

In [29]:
listaarr=np.array((lista, lista))

In [30]:
listaarr

array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]])

In [31]:
?listaarr

In [33]:
el3=np.array((1,2,3))

In [34]:
el3

array([1, 2, 3])

In [35]:
el5=np.array((1,2,3,4,5))

In [36]:
al3+el5

NameError: name 'al3' is not defined

In [37]:
el3+el5

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [38]:
el3.shape

(3,)

In [43]:
el3=np.append(el3,(9,8))

In [44]:
el3

array([1, 2, 3, 9, 8])

In [45]:
el3+el5

array([ 2,  4,  6, 13, 13])

In [46]:
el3.shape(5,1)

TypeError: 'tuple' object is not callable

In [47]:
el3.shape((5,1))

TypeError: 'tuple' object is not callable

In [48]:
el3.shape=(5,1)

In [49]:
el3

array([[1],
       [2],
       [3],
       [9],
       [8]])

In [50]:
import pandas as pd

In [55]:
df=pd.DataFrame(el3)

In [56]:
df

0
0  1
1  2
2  3
3  9
4  8

In [60]:
assert False

AssertionError: 